
program tms;

{$APPTYPE CONSOLE}

{$R *.res}

{$R 'tms_resources.res' 'src\tms_resources.rc'}

uses
  System.SysUtils,
  ULogRotate in '..\common\src\Logger\ULogRotate.pas',
  UMultiLogger in '..\common\src\Logger\UMultiLogger.pas',
  UPlainTextLogger in '..\common\src\Logger\UPlainTextLogger.pas',
  UConsoleLogger in '..\common\src\Logger\UConsoleLogger.pas',
  UFileLogger in '..\common\src\Logger\UFileLogger.pas',
  UHTMLLogger in '..\common\src\Logger\UHTMLLogger.pas',
  ULogger in '..\common\src\Logger\ULogger.pas',
  UCommandLine in '..\common\src\UCommandLine.pas',
  URepositoryInfo in '..\common\src\URepositoryInfo.pas',
  Deget.CommandLine in '..\common\src\Deget\Deget.CommandLine.pas',
  Deget.Compilation in '..\common\src\Deget\Deget.Compilation.pas',
  Deget.CoreTypes in '..\common\src\Deget\Deget.CoreTypes.pas',
  Deget.DelphiInfo in '..\common\src\Deget\Deget.DelphiInfo.pas',
  Deget.DpkFileFormat in '..\common\src\Deget\Deget.DpkFileFormat.pas',
  Deget.Filer.DpkFile in '..\common\src\Deget\Deget.Filer.DpkFile.pas',
  Deget.Filer.DprojFile in '..\common\src\Deget\Deget.Filer.DprojFile.pas',
  Deget.FileUtils in '..\common\src\Deget\Deget.FileUtils.pas',
  Deget.IDEInfo in '..\common\src\Deget\Deget.IDEInfo.pas',
  Deget.IDETypes in '..\common\src\Deget\Deget.IDETypes.pas',
  Deget.IDEUtils in '..\common\src\Deget\Deget.IDEUtils.pas',
  Deget.Nullable in '..\common\src\Deget\Deget.Nullable.pas',
  Deget.PackageConfig in '..\common\src\Deget\Deget.PackageConfig.pas',
  Deget.Registry in '..\common\src\Deget\Deget.Registry.pas',
  BBCmd in '..\common\src\BBYaml\BBCmd.pas',
  BBYaml in '..\common\src\BBYaml\BBYaml.pas',
  BBClasses in '..\common\src\BBYaml\BBClasses.pas',
  UAppTerminated in '..\common\src\UAppTerminated.pas',
  UTmsBuildSystemUtils in '..\common\src\System\UTmsBuildSystemUtils.pas',
  Deget.Filer.Types in '..\common\src\Deget\Deget.Filer.Types.pas',
  UWindowsPath in '..\common\src\System\UWindowsPath.pas',
  UOSShortcuts in '..\common\src\System\UOSShortcuts.pas',
  UInsomnia in '..\common\src\System\UInsomnia.pas',
  Deget.Version in '..\common\src\Deget\Deget.Version.pas',
  UHasher in '..\common\src\System\UHasher.pas',
  Deget.Filer.DprFile in '..\common\src\Deget\Deget.Filer.DprFile.pas',
  Commands.SelfUpdate in 'src\Commands\Commands.SelfUpdate.pas',
  Fetching.Manager in 'src\Fetching\Fetching.Manager.pas',
  Commands.Logging in 'src\Commands\Commands.Logging.pas',
  UProjectLoaderStateMachine in 'src\Project\UProjectLoaderStateMachine.pas',
  Commands.CommonOptions in 'src\Commands\Commands.CommonOptions.pas',
  UConfigLoader in 'src\Config\UConfigLoader.pas',
  Commands.GlobalConfig in 'src\Commands\Commands.GlobalConfig.pas',
  Removal.FolderDeleter in 'src\Removal\Removal.FolderDeleter.pas',
  Removal.Manager in 'src\Removal\Removal.Manager.pas',
  Commands.Termination in 'src\Commands\Commands.Termination.pas',
  UParallelProjectBuilder in 'src\Builder\UParallelProjectBuilder.pas',
  UProjectDefinition in 'src\Project\UProjectDefinition.pas',
  UStandardNaming in 'src\Naming\UStandardNaming.pas',
  UNaming in 'src\Naming\UNaming.pas',
  UMsBuildInstaller in 'src\Installers\UMsBuildInstaller.pas',
  ULazarusInstaller in 'src\Installers\ULazarusInstaller.pas',
  UInstaller in 'src\Installers\UInstaller.pas',
  UDelphiInstaller in 'src\Installers\UDelphiInstaller.pas',
  UDcc32Installer in 'src\Installers\UDcc32Installer.pas',
  UFileHasher in 'src\FileHash\UFileHasher.pas',
  Downloads.VersionManager in 'src\Downloads\Downloads.VersionManager.pas',
  UProjectBuildInfo in 'src\BuildInfo\UProjectBuildInfo.pas',
  UPlatformBuildInfo in 'src\BuildInfo\UPlatformBuildInfo.pas',
  UProjectAnalyzer in 'src\Analyzer\UProjectAnalyzer.pas',
  UPackageFinder in 'src\Analyzer\UPackageFinder.pas',
  UPackageCache in 'src\Analyzer\UPackageCache.pas',
  UMain in 'src\UMain.pas',
  Status.Manager in 'src\Status\Status.Manager.pas',
  Commands.ListRemote in 'src\Commands\Commands.ListRemote.pas',
  UProjectInstaller in 'src\Builder\UProjectInstaller.pas',
  Commands.List in 'src\Commands\Commands.List.pas',
  UProjectLoader in 'src\Project\UProjectLoader.pas',
  Fetching.InstallInfo in 'src\Fetching\Fetching.InstallInfo.pas',
  UBuildSummary in 'src\Builder\UBuildSummary.pas',
  UProjectUninstaller in 'src\Builder\UProjectUninstaller.pas',
  UProjectList in 'src\Project\UProjectList.pas',
  Commands.Update in 'src\Commands\Commands.Update.pas',
  Commands.Fetch in 'src\Commands\Commands.Fetch.pas',
  Commands.Build in 'src\Commands\Commands.Build.pas',
  Actions.Build in 'src\Actions\Actions.Build.pas',
  Commands.Config in 'src\Commands\Commands.Config.pas',
  Commands.Credentials in 'src\Commands\Commands.Credentials.pas',
  Commands.Install in 'src\Commands\Commands.Install.pas',
  UConfigLoaderStateMachine in 'src\Config\UConfigLoaderStateMachine.pas',
  UConfigDefinition in 'src\Config\UConfigDefinition.pas',
  UConfigFolders in 'src\Config\UConfigFolders.pas',
  UIDEBuildInfo in 'src\BuildInfo\UIDEBuildInfo.pas',
  Actions.Fetch in 'src\Actions\Actions.Fetch.pas',
  Removal.Item in 'src\Removal\Removal.Item.pas',
  UIDEUtils in 'src\Builder\UIDEUtils.pas',
  UFileSystemPersistence in 'src\Persistence\UFileSystemPersistence.pas',
  Fetching.ParallelDownloader in 'src\Fetching\Fetching.ParallelDownloader.pas',
  UCredentials in 'src\Repository\UCredentials.pas',
  Fetching.FetchItem in 'src\Fetching\Fetching.FetchItem.pas',
  URepositoryManager in 'src\Repository\URepositoryManager.pas',
  Fetching.Options in 'src\Fetching\Fetching.Options.pas',
  Fetching.Summary in 'src\Fetching\Fetching.Summary.pas',
  UProjectInstallerConstants in 'src\Builder\UProjectInstallerConstants.pas',
  UCheckForOldVersions in 'src\System\UCheckForOldVersions.pas',
  UDefines in 'src\Builder\UDefines.pas',
  UUninstallInfo in 'src\Installers\UUninstallInfo.pas',
  UDelphiXE7Installer in 'src\Installers\UDelphiXE7Installer.pas',
  UBuildInfo in 'src\BuildInfo\UBuildInfo.pas',
  UPersistence in 'src\Persistence\UPersistence.pas',
  UNamingList in 'src\Naming\UNamingList.pas',
  UInstallerRegistry in 'src\Installers\UInstallerRegistry.pas',
  UDelphiXEInstaller in 'src\Installers\UDelphiXEInstaller.pas',
  UDelphiXE8Installer in 'src\Installers\UDelphiXE8Installer.pas',
  UDelphiXE6Installer in 'src\Installers\UDelphiXE6Installer.pas',
  UDelphiXE5Installer in 'src\Installers\UDelphiXE5Installer.pas',
  UDelphiXE4Installer in 'src\Installers\UDelphiXE4Installer.pas',
  UDelphiXE3Installer in 'src\Installers\UDelphiXE3Installer.pas',
  UDelphiXE2Installer in 'src\Installers\UDelphiXE2Installer.pas',
  UDelphiTokyoInstaller in 'src\Installers\UDelphiTokyoInstaller.pas',
  UDelphiSydneyInstaller in 'src\Installers\UDelphiSydneyInstaller.pas',
  UDelphiSeattleInstaller in 'src\Installers\UDelphiSeattleInstaller.pas',
  UDelphiRioInstaller in 'src\Installers\UDelphiRioInstaller.pas',
  UDelphiBerlinInstaller in 'src\Installers\UDelphiBerlinInstaller.pas',
  UDelphi7Installer in 'src\Installers\UDelphi7Installer.pas',
  UDelphi6Installer in 'src\Installers\UDelphi6Installer.pas',
  UDelphi2010Installer in 'src\Installers\UDelphi2010Installer.pas',
  UDelphi2009Installer in 'src\Installers\UDelphi2009Installer.pas',
  UDelphi2007Installer in 'src\Installers\UDelphi2007Installer.pas',
  UDelphi2006Installer in 'src\Installers\UDelphi2006Installer.pas',
  UDelphi2005Installer in 'src\Installers\UDelphi2005Installer.pas',
  UDelphi12Installer in 'src\Installers\UDelphi12Installer.pas',
  UDelphi11Installer in 'src\Installers\UDelphi11Installer.pas',
  Fetching.ParallelProjectInfo in 'src\Fetching\Fetching.ParallelProjectInfo.pas',
  UCoreTypes in 'src\Core\UCoreTypes.pas',
  UConfigKeys in 'src\Config\UConfigKeys.pas',
  UProjectBuilderInterface in 'src\Builder\UProjectBuilderInterface.pas',
  UParallelProjectInfo in 'src\Builder\UParallelProjectInfo.pas',
  UParallelDependencies in 'src\Builder\UParallelDependencies.pas',
  USkippedPlatforms in 'src\BuildInfo\USkippedPlatforms.pas',
  UPackageBuildInfo in 'src\BuildInfo\UPackageBuildInfo.pas',
  UFullBuildInfo in 'src\BuildInfo\UFullBuildInfo.pas',
  Commands.Info in 'src\Commands\Commands.Info.pas',
  UJsonPrinter in '..\common\src\UJsonPrinter.pas',
  Deget.RCFileFormat in '..\common\src\Deget\Deget.RCFileFormat.pas',
  Deget.ResFile in '..\common\src\Deget\Deget.ResFile.pas',
  UOSFileLinks in '..\common\src\System\UOSFileLinks.pas',
  Commands.Doctor in 'src\Commands\Commands.Doctor.pas',
  Doctor.Check in 'src\Doctor\Doctor.Check.pas',
  Doctor.WindowsPathCheck in 'src\Doctor\Doctor.WindowsPathCheck.pas',
  Doctor.Run in 'src\Doctor\Doctor.Run.pas',
  Doctor.DelphiEnvironmentCheck in 'src\Doctor\Doctor.DelphiEnvironmentCheck.pas',
  Doctor.LibraryPathCheck in 'src\Doctor\Doctor.LibraryPathCheck.pas',
  Doctor.CorePathCheck in 'src\Doctor\Doctor.CorePathCheck.pas',
  Doctor.MultiIDECheck in 'src\Doctor\Doctor.MultiIDECheck.pas',
  UConsoleUtil in '..\common\src\Logger\UConsoleUtil.pas',
  VCS.Engine.Git in 'src\VCS\VCS.Engine.Git.pas',
  VCS.Registry in 'src\VCS\VCS.Registry.pas',
  VCS.Manager in 'src\VCS\VCS.Manager.pas',
  VCS.Summary in 'src\VCS\VCS.Summary.pas',
  VCS.Engine.Virtual in 'src\VCS\VCS.Engine.Virtual.pas',
  VCS.Engine.Factory in 'src\VCS\VCS.Engine.Factory.pas',
  VCS.CoreTypes in 'src\VCS\VCS.CoreTypes.pas',
  VCS.Engine.Svn in 'src\VCS\VCS.Engine.Svn.pas',
  Commands.RepoRegister in 'src\Commands\Commands.RepoRegister.pas',
  Commands.RepoUnregister in 'src\Commands\Commands.RepoUnregister.pas',
  Commands.RepoList in 'src\Commands\Commands.RepoList.pas',
  USimpleJsonSerializer in '..\common\src\USimpleJsonSerializer.pas',
  Commands.LogView in 'src\Commands\Commands.LogView.pas',
  Decompressor.ZSTD in '..\common\src\Compression\Decompressor.ZSTD.pas',
  ZSTD in '..\common\src\Compression\ZSTD.pas\ZSTD.pas',
  ZSTDLib in '..\common\src\Compression\ZSTD.pas\ZSTDLib.pas',
  TarCommon in '..\common\src\Compression\LibTar\TarCommon.pas',
  TarReader in '..\common\src\Compression\LibTar\TarReader.pas',
  Deget.Filer.CBprojFile in '..\common\src\Deget\Deget.Filer.CBprojFile.pas',
  ULoggerTask in '..\common\src\Logger\ULoggerTask.pas',
  Commands.Uninstall in 'src\Commands\Commands.Uninstall.pas',
  Commands.Uncompress in 'src\Commands\Commands.Uncompress.pas',
  UGenericDecompressor in '..\common\src\Compression\UGenericDecompressor.pas',
  Fetching.InfoFile in '..\common\src\Fetching\Fetching.InfoFile.pas',
  Deget.Filer.ProjectFactory in '..\common\src\Deget\Deget.Filer.ProjectFactory.pas',
  UEnvironmentPath in 'src\System\UEnvironmentPath.pas',
  Util.Replacer in '..\common\src\System\Util.Replacer.pas',
  UConfigWriter in 'src\Config\UConfigWriter.pas',
  Commands.ConfigWrite in 'src\Commands\Commands.ConfigWrite.pas',
  Commands.ConfigRead in 'src\Commands\Commands.ConfigRead.pas',
  VSoft.CommandLine.Options in '..\externals\VSoft.CommandLineParser\Src\VSoft.CommandLine.Options.pas',
  VSoft.CommandLine.Parser in '..\externals\VSoft.CommandLineParser\Src\VSoft.CommandLine.Parser.pas',
  VSoft.CommandLine.Utils in '..\externals\VSoft.CommandLineParser\Src\VSoft.CommandLine.Utils.pas',
  VSoft.CommandLine.CommandDef in '..\externals\VSoft.CommandLineParser\Src\VSoft.CommandLine.CommandDef.pas',
  VSoft.CommandLine.OptionDef in '..\externals\VSoft.CommandLineParser\Src\VSoft.CommandLine.OptionDef.pas',
  ZipFile.Download in 'src\VCS\ZipFile.Download.pas',
  Commands.ServerEnable in 'src\Commands\Commands.ServerEnable.pas',
  Commands.ServerList in 'src\Commands\Commands.ServerList.pas',
  Commands.ServerAdd in 'src\Commands\Commands.ServerAdd.pas',
  Commands.ServerRemove in 'src\Commands\Commands.ServerRemove.pas',
  VCS.Engine.ZipFile in 'src\VCS\VCS.Engine.ZipFile.pas',
  Package.Creator in 'src\Packages\Package.Creator.pas';

begin
  try
    UMain.Run;
  except
    on E: Exception do
    begin
      if ExitCode = 0 then
        ExitCode := 10;

      Writeln(E.Message);
    end;
  end;
end.
