unit Snapshot.Writer;

interface
uses Classes, SysUtils, Status.Manager, Generics.Collections, IOUtils;

procedure WriteSnapshot(const FileName: string; const Products: TList<TProductStatus>);

implementation
uses UTmsBuildSystemUtils, BBStrings;

procedure WriteSnapshot(const FileName: string; const Products: TList<TProductStatus>);
begin
  var SnapshotFolder := TPath.GetDirectoryName(FileName);
  if SnapshotFolder.Trim <> '' then
  begin
    if not TDirectory.Exists(SnapshotFolder)
      then TDirectory_CreateDirectory(SnapshotFolder);
  end;

  var Writer := TStreamWriter.Create(FileName, false, TUTF8NoBOMEncoding.Instance);
  try
    Writer.WriteLine('# This file was generated by TMS SmartSetup.');
    Writer.WriteLine('# use tms restore [-with-versions] to restore the products [and versions] in this file.');
    Writer.WriteLine;
    //Products are already sorted. If not we would have to sort them here so the file is always the same.
    Writer.WriteLine('products:');

    for var Product in Products do
    begin
      Writer.WriteLine('  - ' + BBYamlEscapeString(Product.Id, false) + ':');
      Writer.WriteLine('      version: ' + BBYamlEscapeString(Product.InstalledVersion, false));
      Writer.WriteLine('      server: ' + BBYamlEscapeString(Product.Server, false));
      Writer.WriteLine('      url: ' + BBYamlEscapeString(Product.Project.Application.Url, false)); // For audit purposes
      Writer.WriteLine('      pinned: ' + BoolToStr(Product.Pinned, true).ToLowerInvariant);
      Writer.WriteLine;
    end;

  finally
    Writer.Free;
  end;
end;

end.
